# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Basic dependabot.yml file with
# minimum configuration for one package manager

version: 2
updates:
  # Enable version updates for bundler
  - package-ecosystem: "bundler"
    # Look for `Gemfile` and `Gemfile.lock` file in the `root` directory
    directory: "/"
    # Check for updates every month (1st day of month)
    schedule:
      interval: "monthly"
